An error occurred while trying to fetch botp/stable-diffusion-v1-5-inpainting: botp/stable-diffusion-v1-5-inpainting does not appear to have a file named diffusion_pytorch_model.safetensors.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Processing batches:   1%|â–‹                                                           | 8/654 [00:05<07:47,  1.38it/s]
Traceback (most recent call last):
  File "/home/CATDF-Diffusion/script_run/../train.py", line 284, in <module>
    main()
  File "/home/CATDF-Diffusion/script_run/../train.py", line 223, in main
    embedding.save_embeddings_to_npz('cuda')
  File "/home/CATDF-Diffusion/embedding_data.py", line 35, in save_embeddings_to_npz
    for i, batch in tqdm(enumerate(self.data_loader), total=len(self.data_loader), desc="Processing batches"):
  File "/opt/conda/envs/chaos/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/opt/conda/envs/chaos/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/opt/conda/envs/chaos/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/envs/chaos/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/chaos/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/CATDF-Diffusion/dataset_deepfuniture_img2img.py", line 339, in __getitem__
    batch = self.make_data(image_path,fill_image, bbox_string, mask_string)
  File "/home/CATDF-Diffusion/dataset_deepfuniture_img2img.py", line 296, in make_data
    mask_image = self.create_bbox_mask(pixel_values, bboxes_annotation)
  File "/home/CATDF-Diffusion/dataset_deepfuniture_img2img.py", line 200, in create_bbox_mask
    mask.putpixel((x, y), 255)  # Set bbox region to white
  File "/opt/conda/envs/chaos/lib/python3.10/site-packages/PIL/Image.py", line 1974, in putpixel
    if self.readonly:
KeyboardInterrupt
